spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Hollyarea173MySQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
  file:
    path: log/blog-dev.log
server:
  port: 8081
  servlet:
    context-path: /unit


